<a href="https://colab.research.google.com/github/runtorain/GenerativeDeepLearning/blob/main/241227_CNN_Weigth_bias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

# Define the convolutional layer
conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)

# Print the randomly initialized filters (weights)
print("Shape of filters:", conv1.weight.shape)  # (32, 3, 3, 3)
print("Filters (randomly initialized):")
print(conv1.weight)  # Weights for all 32 filters


Shape of filters: torch.Size([32, 3, 3, 3])
Filters (randomly initialized):
Parameter containing:
tensor([[[[ 8.6841e-03,  4.6154e-02,  1.6583e-01],
          [ 7.8240e-02,  4.1690e-02,  1.0193e-01],
          [ 1.3041e-01,  8.2457e-02,  1.0496e-01]],

         [[ 1.3216e-01,  7.0619e-02,  1.3917e-01],
          [-1.2678e-01, -3.5965e-02, -2.6983e-02],
          [ 7.6212e-02, -5.2580e-02, -7.7925e-02]],

         [[ 5.8184e-02,  4.5373e-02, -1.5765e-01],
          [ 3.4225e-02, -1.4291e-01,  1.1529e-01],
          [ 8.6000e-02,  1.1340e-01,  4.4992e-02]]],


        [[[ 8.5262e-02,  8.2254e-02, -1.8632e-01],
          [-8.3046e-03, -1.4272e-01, -6.7007e-02],
          [-1.5326e-01, -1.4342e-01,  9.1821e-02]],

         [[ 8.1121e-02, -1.4197e-01, -1.8215e-01],
          [-8.5743e-02, -1.6904e-01,  9.6249e-02],
          [ 3.5139e-02,  2.0879e-02,  4.4121e-02]],

         [[ 1.0116e-01, -5.8695e-02,  1.8178e-01],
          [ 1.3020e-01, -1.6882e-01,  5.0423e-03],
          [-9.8768e-03,

In [ ]:
# Get the first filter
first_filter = conv1.weight[0]
print("First filter (shape):", first_filter.shape)  # (3, 3, 3)
print(first_filter)  # Weights for the first filter


First filter (shape): torch.Size([3, 3, 3])
tensor([[[ 0.0087,  0.0462,  0.1658],
         [ 0.0782,  0.0417,  0.1019],
         [ 0.1304,  0.0825,  0.1050]],

        [[ 0.1322,  0.0706,  0.1392],
         [-0.1268, -0.0360, -0.0270],
         [ 0.0762, -0.0526, -0.0779]],

        [[ 0.0582,  0.0454, -0.1577],
         [ 0.0342, -0.1429,  0.1153],
         [ 0.0860,  0.1134,  0.0450]]], grad_fn=<SelectBackward0>)


In [ ]:
conv1.weight[1]

tensor([[[ 0.0853,  0.0823, -0.1863],
         [-0.0083, -0.1427, -0.0670],
         [-0.1533, -0.1434,  0.0918]],

        [[ 0.0811, -0.1420, -0.1821],
         [-0.0857, -0.1690,  0.0962],
         [ 0.0351,  0.0209,  0.0441]],

        [[ 0.1012, -0.0587,  0.1818],
         [ 0.1302, -0.1688,  0.0050],
         [-0.0099, -0.1908,  0.1600]]], grad_fn=<SelectBackward0>)

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Define the model
class SimpleCNN(nn.Module):
    def __init__(self, num_classes=10):  # Adding num_classes for better usability
        super(SimpleCNN, self).__init__()

        # Convolutional layers with BatchNorm and LeakyReLU
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1, stride=1)
        self.bn1 = nn.BatchNorm2d(32)

        self.conv2 = nn.Conv2d(32, 32, kernel_size=3, padding=1, stride=2)
        self.bn2 = nn.BatchNorm2d(32)

        self.conv3 = nn.Conv2d(32, 64, kernel_size=3, padding=1, stride=1)
        self.bn3 = nn.BatchNorm2d(64)

        self.conv4 = nn.Conv2d(64, 64, kernel_size=3, padding=1, stride=2)
        self.bn4 = nn.BatchNorm2d(64)

        # Fully connected layers
        self.fc1 = nn.Linear(64 * 8 * 8, 128)
        self.fc2 = nn.Linear(128, num_classes)

        # Dropout layer
        self.dropout = nn.Dropout(p=0.5)

    def forward(self, x):
        x = F.leaky_relu(self.bn1(self.conv1(x)), negative_slope=0.01)
        x = F.leaky_relu(self.bn2(self.conv2(x)), negative_slope=0.01)
        x = F.leaky_relu(self.bn3(self.conv3(x)), negative_slope=0.01)
        x = F.leaky_relu(self.bn4(self.conv4(x)), negative_slope=0.01)

        x = x.view(x.size(0), -1)  # Flatten the tensor
        x = F.leaky_relu(self.fc1(x), negative_slope=0.01)
        x = self.dropout(x)
        x = self.fc2(x)

        return F.softmax(x, dim=1)




In [ ]:
# Instantiate the model
model = SimpleCNN(num_classes=10)

# Access weights of conv2
conv2_weights = model.conv2.weight
print("conv2 weights shape:", conv2_weights.shape)
print("conv2 weights:", conv2_weights)


conv2 weights shape: torch.Size([32, 32, 3, 3])
conv2 weights: Parameter containing:
tensor([[[[ 0.0109, -0.0463, -0.0056],
          [ 0.0382, -0.0350,  0.0554],
          [ 0.0583, -0.0453,  0.0536]],

         [[ 0.0034, -0.0188,  0.0302],
          [ 0.0271,  0.0007,  0.0453],
          [ 0.0187,  0.0554,  0.0583]],

         [[ 0.0483,  0.0311, -0.0553],
          [-0.0514,  0.0250,  0.0397],
          [-0.0143,  0.0327, -0.0353]],

         ...,

         [[ 0.0347, -0.0524, -0.0060],
          [-0.0272, -0.0302, -0.0534],
          [ 0.0464,  0.0521, -0.0204]],

         [[-0.0506, -0.0033,  0.0326],
          [-0.0171, -0.0082, -0.0521],
          [ 0.0146,  0.0417,  0.0428]],

         [[ 0.0010, -0.0210, -0.0474],
          [ 0.0571, -0.0514, -0.0175],
          [ 0.0387,  0.0038, -0.0093]]],


        [[[ 0.0057,  0.0100, -0.0491],
          [-0.0128, -0.0151, -0.0126],
          [-0.0277,  0.0145, -0.0489]],

         [[-0.0524, -0.0554, -0.0528],
          [-0.0460,  0.021

In [ ]:
# Access the bias of conv2
conv2_bias = model.conv2.bias

# Print the shape of the bias
print("conv2 bias shape:", conv2_bias.shape)

# Print the bias values
print("conv2 bias:", conv2_bias)


conv2 bias shape: torch.Size([32])
conv2 bias: Parameter containing:
tensor([ 0.0008,  0.0192,  0.0552,  0.0092, -0.0149, -0.0294, -0.0089, -0.0468,
        -0.0189, -0.0096, -0.0142,  0.0039,  0.0278,  0.0427, -0.0552,  0.0089,
         0.0420, -0.0087,  0.0330, -0.0098, -0.0252, -0.0261, -0.0214, -0.0397,
        -0.0461,  0.0538,  0.0243,  0.0069, -0.0104, -0.0428,  0.0553, -0.0429],
       requires_grad=True)


In [ ]:
# Access weights of bn2
bn2_weights = model.bn2.weight
print("bn2 weights shape:", bn2_weights.shape)
print("bn2 weights:", bn2_weights)


bn2 weights shape: torch.Size([32])
bn2 weights: Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       requires_grad=True)


In [ ]:
# Access biases of bn2
bn2_biases = model.bn2.bias
print("bn2 biases shape:", bn2_biases.shape)
print("bn2 biases:", bn2_biases)

bn2 biases shape: torch.Size([32])
bn2 biases: Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)


In [ ]:
bn2_beta = model.bn2.bias
print("bn2 beta shape:", bn2_beta.shape)
print("bn2 beta:", bn2_beta)


bn2 beta shape: torch.Size([32])
bn2 beta: Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)


In [ ]:
fc1_bias = model.fc1.bias
print("fc1 bias shape:", fc1_bias.shape)
print("fc1 bias:", fc1_bias)

fc1 bias shape: torch.Size([128])
fc1 bias: Parameter containing:
tensor([ 7.8672e-03, -7.7477e-04, -4.1648e-04, -9.2469e-03, -5.2715e-03,
         1.3397e-02,  1.4264e-02,  7.5427e-03,  5.5419e-03, -8.8787e-03,
         5.8303e-03,  1.4671e-02,  1.4158e-02,  1.4447e-02,  1.2265e-02,
        -3.4191e-03, -3.3739e-03, -1.2574e-02,  1.7419e-03,  9.5813e-03,
        -2.6628e-03,  9.0253e-03,  1.5263e-02,  1.3931e-02, -1.0381e-02,
         3.2031e-03,  4.8027e-03, -1.1688e-02, -9.1845e-03,  1.3487e-03,
        -1.4477e-02, -1.5467e-02,  5.4160e-03,  1.4900e-02, -1.3505e-03,
         2.8155e-03,  1.2699e-03,  6.7294e-03,  2.4562e-03, -8.0154e-04,
         1.6268e-03,  8.2336e-03,  4.2289e-03, -6.6956e-03, -9.8914e-03,
        -7.7463e-03,  6.3925e-03, -2.8262e-03, -7.5844e-03,  8.8819e-04,
         6.8694e-03,  1.5409e-02,  8.5374e-03, -8.1603e-03,  1.6751e-03,
         1.4430e-02,  4.1046e-03,  1.0832e-02, -1.1803e-02, -1.0386e-02,
        -1.0370e-03, -9.0959e-03, -1.1097e-02,  2.1075e-03

In [ ]:
fc2_bias = model.fc2.bias
print("fc1 bias shape:", fc2_bias.shape)
print("fc1 bias:", fc2_bias)

fc1 bias shape: torch.Size([10])
fc1 bias: Parameter containing:
tensor([-0.0658,  0.0220,  0.0742, -0.0462,  0.0247, -0.0677,  0.0271, -0.0553,
         0.0648, -0.0259], requires_grad=True)


In [ ]:
fc2_weight = model.fc2.weight
print("fc1 weight shape:", fc2_weight.shape)
print("fc1 weight:", fc2_weight)

fc1 weight shape: torch.Size([10, 128])
fc1 weight: Parameter containing:
tensor([[-0.0112,  0.0265,  0.0745,  ...,  0.0748, -0.0219,  0.0330],
        [-0.0257,  0.0749,  0.0537,  ..., -0.0552, -0.0264, -0.0357],
        [ 0.0247,  0.0379, -0.0143,  ..., -0.0641,  0.0587,  0.0726],
        ...,
        [-0.0085,  0.0395, -0.0290,  ...,  0.0169,  0.0452,  0.0663],
        [ 0.0680,  0.0323, -0.0884,  ..., -0.0874,  0.0596,  0.0128],
        [-0.0544, -0.0160, -0.0283,  ...,  0.0784, -0.0772,  0.0670]],
       requires_grad=True)


In [ ]:
import torch

# Example input tensor of shape (2, 2, 3, 3)
x = torch.tensor([[
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
], [
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]],
    [[28, 29, 30], [31, 32, 33], [34, 35, 36]]
]])

print("Before flattening:")
print("Shape:", x.shape)
print(x)

# Flattening
x_flattened = x.view(x.size(0), -1)

print("\nAfter flattening:")
print("Shape:", x_flattened.shape)
print(x_flattened)


Before flattening:
Shape: torch.Size([2, 2, 3, 3])
tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],

         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]],


        [[[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]],

         [[28, 29, 30],
          [31, 32, 33],
          [34, 35, 36]]]])

After flattening:
Shape: torch.Size([2, 18])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]])
