<a href="https://colab.research.google.com/github/runtorain/GenerativeDeepLearning/blob/main/CNN_Weigth_bias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

# Define the convolutional layer
conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)

# Print the randomly initialized filters (weights)
print("Shape of filters:", conv1.weight.shape)  # (32, 3, 3, 3)
print("Filters (randomly initialized):")
print(conv1.weight)  # Weights for all 32 filters


Shape of filters: torch.Size([32, 3, 3, 3])
Filters (randomly initialized):
Parameter containing:
tensor([[[[-3.8139e-02, -5.2125e-02,  1.6078e-01],
          [ 1.8131e-02,  1.3234e-01, -8.1064e-02],
          [ 3.6040e-02, -8.4873e-02, -4.4819e-02]],

         [[-8.3811e-02,  1.2061e-01, -5.7088e-03],
          [-3.3463e-02,  1.7178e-01, -1.5005e-01],
          [-1.4239e-01, -4.4975e-02,  3.2349e-02]],

         [[ 5.3413e-02,  1.7946e-02,  1.5286e-01],
          [ 1.4992e-01, -1.5575e-02,  8.2106e-02],
          [ 8.2992e-02,  1.9181e-01,  8.2765e-02]]],


        [[[-3.5660e-02, -7.3696e-03,  1.5096e-01],
          [ 1.5056e-01,  1.1732e-01, -1.7224e-01],
          [-1.3417e-01,  1.2372e-01,  1.2402e-01]],

         [[ 1.6532e-01,  1.4212e-03, -4.2111e-02],
          [ 1.8235e-02,  8.7422e-02,  9.8611e-02],
          [-1.4589e-01, -2.1871e-02, -1.2903e-01]],

         [[ 1.4314e-01,  7.6662e-02, -1.4035e-01],
          [-1.6852e-01,  1.4076e-01, -1.6938e-01],
          [ 7.9138e-02,

In [2]:
# Get the first filter
first_filter = conv1.weight[0]
print("First filter (shape):", first_filter.shape)  # (3, 3, 3)
print(first_filter)  # Weights for the first filter


First filter (shape): torch.Size([3, 3, 3])
tensor([[[-0.0381, -0.0521,  0.1608],
         [ 0.0181,  0.1323, -0.0811],
         [ 0.0360, -0.0849, -0.0448]],

        [[-0.0838,  0.1206, -0.0057],
         [-0.0335,  0.1718, -0.1501],
         [-0.1424, -0.0450,  0.0323]],

        [[ 0.0534,  0.0179,  0.1529],
         [ 0.1499, -0.0156,  0.0821],
         [ 0.0830,  0.1918,  0.0828]]], grad_fn=<SelectBackward0>)


In [3]:
conv1.weight[1]

tensor([[[-0.0357, -0.0074,  0.1510],
         [ 0.1506,  0.1173, -0.1722],
         [-0.1342,  0.1237,  0.1240]],

        [[ 0.1653,  0.0014, -0.0421],
         [ 0.0182,  0.0874,  0.0986],
         [-0.1459, -0.0219, -0.1290]],

        [[ 0.1431,  0.0767, -0.1404],
         [-0.1685,  0.1408, -0.1694],
         [ 0.0791, -0.0665,  0.0459]]], grad_fn=<SelectBackward0>)

In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Define the model
class SimpleCNN(nn.Module):
    def __init__(self, num_classes=10):  # Adding num_classes for better usability
        super(SimpleCNN, self).__init__()

        # Convolutional layers with BatchNorm and LeakyReLU
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1, stride=1)
        self.bn1 = nn.BatchNorm2d(32)

        self.conv2 = nn.Conv2d(32, 32, kernel_size=3, padding=1, stride=2)
        self.bn2 = nn.BatchNorm2d(32)

        self.conv3 = nn.Conv2d(32, 64, kernel_size=3, padding=1, stride=1)
        self.bn3 = nn.BatchNorm2d(64)

        self.conv4 = nn.Conv2d(64, 64, kernel_size=3, padding=1, stride=2)
        self.bn4 = nn.BatchNorm2d(64)

        # Fully connected layers
        self.fc1 = nn.Linear(64 * 8 * 8, 128)
        self.fc2 = nn.Linear(128, num_classes)

        # Dropout layer
        self.dropout = nn.Dropout(p=0.5)

    def forward(self, x):
        x = F.leaky_relu(self.bn1(self.conv1(x)), negative_slope=0.01)
        x = F.leaky_relu(self.bn2(self.conv2(x)), negative_slope=0.01)
        x = F.leaky_relu(self.bn3(self.conv3(x)), negative_slope=0.01)
        x = F.leaky_relu(self.bn4(self.conv4(x)), negative_slope=0.01)

        x = x.view(x.size(0), -1)  # Flatten the tensor
        x = F.leaky_relu(self.fc1(x), negative_slope=0.01)
        x = self.dropout(x)
        x = self.fc2(x)

        return F.softmax(x, dim=1)




In [5]:
# Instantiate the model
model = SimpleCNN(num_classes=10)

# Access weights of conv2
conv2_weights = model.conv2.weight
print("conv2 weights shape:", conv2_weights.shape)
print("conv2 weights:", conv2_weights)


conv2 weights shape: torch.Size([32, 32, 3, 3])
conv2 weights: Parameter containing:
tensor([[[[-2.5086e-03,  5.5154e-02,  6.9379e-03],
          [ 4.1918e-02,  3.7341e-02, -2.5850e-02],
          [ 1.6669e-02,  8.2253e-03, -2.9470e-02]],

         [[ 4.4081e-02, -2.2667e-02,  4.5843e-03],
          [-3.6730e-02, -2.7871e-02, -3.7592e-02],
          [ 5.7849e-02,  1.7424e-02,  4.8141e-02]],

         [[-4.5917e-02, -4.2669e-02,  4.6643e-02],
          [-2.0176e-02, -5.0617e-02,  3.5629e-02],
          [-3.9846e-03, -3.5214e-02, -1.4466e-02]],

         ...,

         [[ 4.0038e-02, -4.9368e-03, -1.3734e-02],
          [-3.7193e-02,  4.1340e-02,  7.6589e-03],
          [ 2.7336e-02, -2.0771e-02,  7.8907e-03]],

         [[ 1.6902e-02,  1.0429e-02,  4.1348e-02],
          [ 5.7561e-02, -1.5608e-03, -1.7089e-03],
          [ 1.0930e-02,  5.8240e-02,  3.5285e-02]],

         [[ 1.0554e-02, -3.9291e-02,  6.9928e-03],
          [ 4.1114e-02,  5.6191e-03,  5.4536e-02],
          [-2.9290e-02,

In [6]:
# Access weights of bn2
bn2_weights = model.bn2.weight
print("bn2 weights shape:", bn2_weights.shape)
print("bn2 weights:", bn2_weights)


bn2 weights shape: torch.Size([32])
bn2 weights: Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       requires_grad=True)


In [7]:
# Access biases of bn2
bn2_biases = model.bn2.bias
print("bn2 biases shape:", bn2_biases.shape)
print("bn2 biases:", bn2_biases)

bn2 biases shape: torch.Size([32])
bn2 biases: Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)
